url: http://voyage.zemati.eu
baseurl: ""
title: Poux et puces
tagline: Notre blog de voyage
description: >
  Le blog de voyage de Marion, Nicolas et Indiana.

author:
  name: Nicolas Zermati
  email: nicoolas25@gmail.com

paginate: 5
markdown: kramdown
